version: 2
updates:
  # Maintain dependencies for Go, checking daily
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    # Assign reviewers to Go PRs
    reviewers:
      - zelyo-operator-bot
    # Group minor and patch updates
    groups:
      go-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain GitHub Actions dependencies, checking weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group minor and patch updates
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain Docker dependencies, checking weekly
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    # Group minor and patch updates
    groups:
      docker-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
