apiVersion: aotanami.com/v1alpha1
kind: NotificationChannel
metadata:
  labels:
    app.kubernetes.io/name: aotanami
    app.kubernetes.io/managed-by: kustomize
  name: notificationchannel-sample
  namespace: aotanami-system
spec:
  type: slack
  credentialSecret: slack-token
  severityFilter: medium
  rateLimit:
    maxPerHour: 60
    aggregateSeconds: 30
  slack:
    channel: "#aotanami-alerts"
