apiVersion: aotanami.com/v1alpha1
kind: CostPolicy
metadata:
  labels:
    app.kubernetes.io/name: aotanami
    app.kubernetes.io/managed-by: kustomize
  name: costpolicy-sample
spec:
  # TODO(user): Add fields here
